// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DomInstruction = { "CreateElement": { id: string, tag: string, } } | { "SetAttribute": { id: string, attr: string, value: string, } } | { "RemoveAttribute": { id: string, attr: string, } } | { "SetText": { id: string, text: string, } } | { "AppendChild": { parent_id: string, child_id: string, } } | { "RemoveChild": { parent_id: string, child_id: string, } } | { "ReplaceChild": { parent_id: string, old_id: string, new_id: string, } };
