// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DomNode = { "Element": { tag: string, attrs: Array<[string, string]>, children: Array<DomNode>, } } | { "Text": string };
