// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * High-Level Intermediate Representation (HLIR).
 * Represents conceptual application-level transitions.
 */
export type HLIR = { "type": "UpdateState", "payload": { patch: string, } } | { "type": "Navigate", "payload": { path: string, } } | { "type": "Notify", "payload": { level: string, msg: string, } } | { "type": "InvokeJS", "payload": { func: string, args: string, } } | { "type": "SyncData", "payload": { key: string, value: string, } };
