// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HLIR } from "./HLIR";
import type { LLIR } from "./LLIR";

/**
 * A package of IR instructions resulting from a single action.
 */
export type IRBundle = { 
/**
 * The version of the IR schema used.
 */
version: string, 
/**
 * High-level application transitions.
 */
effects: Array<HLIR>, 
/**
 * Low-level atomic DOM mutations.
 */
llir: Array<LLIR>, };
