// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KanbanTask } from "./KanbanTask";

/**
 * Commands sent from the TS Bridge to the Rust core.
 */
export type IRCommand = { "type": "SampleTaskFetch" } | { "type": "SampleTaskSubmit", "payload": { input: string, } } | { "type": "Add", "payload": { a: number, b: number, } } | { "type": "Fibonacci", "payload": { n: number, } } | { "type": "Factorial", "payload": { n: number, } } | { "type": "ReverseString", "payload": { text: string, } } | { "type": "PalindromeCheck", "payload": { text: string, } } | { "type": "Greet", "payload": { name: string, } } | { "type": "ReportAnomaly", "payload": { message: string, } } | { "type": "RulesQuery" } | { "type": "SystemFetch" } | { "type": "KanbanFetch" } | { "type": "MoveTask", "payload": { id: string, col: string, } } | { "type": "AddTask", "payload": { title: string, priority: string, tags: Array<string>, } } | { "type": "DeleteTask", "payload": { id: string, } } | { "type": "EditTask", "payload": { id: string, title: string, priority: string, tags: Array<string>, } } | { "type": "SyncKanban", "payload": { tasks: Array<KanbanTask>, } } | { "type": "PerformDiff", "payload": { old_html: string, new_html: string, } };
