// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomInstruction } from "./DomInstruction";
import type { KanbanTask } from "./KanbanTask";
import type { SampleTaskState } from "./SampleTaskState";
import type { SystemInfo } from "./SystemInfo";

/**
 * Results returned from the Rust core to the TS Bridge.
 */
export type IRResult = { "type": "SampleTaskData", "payload": SampleTaskState } | { "type": "Number", "payload": number } | { "type": "Void" } | { "type": "Error", "payload": { message: string, } } | { "type": "Rules", "payload": { schema: string, } } | { "type": "SystemInfo", "payload": SystemInfo } | { "type": "KanbanData", "payload": Array<KanbanTask> } | { "type": "DiffResult", "payload": Array<DomInstruction> };
