// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KanbanTask = { id: string, title: string, col: string, priority: string, tags: Array<string>, };
