// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Low-Level Intermediate Representation (LLIR).
 * Represents atomic DOM mutations or system calls.
 */
export type LLIR = { "type": "UpdateText", "payload": { id: string, text: string, } } | { "type": "SetAttribute", "payload": { id: string, attr: string, value: string, } } | { "type": "RemoveAttribute", "payload": { id: string, attr: string, } } | { "type": "AddClass", "payload": { id: string, class: string, } } | { "type": "RemoveClass", "payload": { id: string, class: string, } } | { "type": "ToggleClass", "payload": { id: string, class: string, } } | { "type": "SetStyle", "payload": { id: string, prop: string, value: string, } } | { "type": "TriggerEvent", "payload": { id: string, event: string, } } | { "type": "Log", "payload": { message: string, } } | { "type": "Anomaly", "payload": { code: string, details: string, } };
