// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemInfo = { os: string, browser: string, cpu_cores: number, ram_gb: number, screen_res: string, gpu: string, uptime_ms: number, language: string, };
